homelab:
  hosts:
    arr:
      ansible_host: 192.168.1.201
      ansible_user: ccalifice
      ansible_password: malvado6696
    services:
      ansible_host: 192.168.1.202
      ansible_user: ccalifice
      ansible_password: malvado6696
    pi:
      ansible_host: 192.168.1.199
      ansible_user: dietpi
      ansible_password: malvado6696